### PR TITLE
Fix #4363

### LINKED ISSUE #4363: Article Viewer throws errors when article doesn't exist
### What is happening?
When viewing a student in the Assignments & Exercises view on the Students tab, if the student has an assigned article then there is an Article Viewer icon for it. However, if the assigned article doesn't exist yet, this is useless and just shows an error message when viewed.

### To Reproduce

* In a course, assign someone an article title that doesn't exist.
* View that user from the Students tab and click the Article Viewer for that assignment

### Expected behavior

Article Viewer should not be clickable if the article doesn't exist yet, and mousing over it should show a message indicating that the article doesn't exist.

### PR DESCRIPTION
**Pull request by rohitgeddam**
disable Article Viewer button if the article doesn't exist.

Fix article viewer button error

Disable the article viewer button when the article is not valid

Add Style for Article Viewer Disabled Button

clean syntax

NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
* Disable Article Viewer button when the article dosen't exist.
* Add styling for disabled viewer button

## Screenshots
Before:

After:
Screenshot 2021-03-03 at 6 25 27 PM

## Open questions and concerns
* right now the string "Article Dosen't Exist" is hardcoded into the IconOpener component, Is there any other place where i 
place that string?

### CODE REVIEW

**Comment by rohitgeddam** [comment]
Screenshot 2021-03-03 at 6 25 27 PM

* Disabled the button if the article doesn't exist.
* I am checking if props.article_id is null or not.
* right now the string "Article Dosen't Exist" is hardcoded into the IconOpener component, Is there any other place where i 
place that string?

File: app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx [hunk 1]
```diff
@@ -27,6 +27,7 @@ import colors from '@components/common/ArticleViewer/constants/colors';
 
 // Actions
 import { resetNeedHelpAlert, submitBadWorkAlert } from '~/app/assets/javascripts/actions/alert_actions.js';
+import { Button } from 'react-scroll';
```
Comment (ragesoss) [inline app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx:30]: What is this for?

File: app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx [hunk 2]
```diff
@@ -272,11 +273,20 @@ export class ArticleViewer extends React.Component {
         );
       }
       return (
+       this.props.article.article_id ?
```
Comment (ragesoss) [inline app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx:276]: I suggest moving all the conditional logic into IconOpener. We really want to avoid making ArticleViewer any more complex than it already is. You can pass the article as a prop, and then let it determine its own `disabled` state.

File: app/assets/javascripts/components/common/ArticleViewer/components/IconOpener.jsx [hunk 3]
```diff
@@ -1,19 +1,27 @@
...
+    <button 
+      onClick={showArticle}
+      aria-label="Open Article Viewer"
+      className={"icon " + ( disabled ? "icon-article-viewer-disabled" : "icon-article-viewer" ) }
+      disabled={disabled}
+     />
     <div className="tooltip tooltip-center dark large">
-      <p>{showButtonLabel()}</p>
+      {
+        disabled ? <p>Article Doesn't Exist</p> : <p>{showButtonLabel()}</p>
```
Comment (ragesoss) [inline app/assets/javascripts/components/common/ArticleViewer/components/IconOpener.jsx:14]: This message should be done via the i18n system so that it can be translated.

**Review by ragesoss — COMMENTED** [review]
The hard-coded message string should be added to `en.yml`, which can then be rendered with `I18n.t`. (There are some examples of this in ArticleViewer.jsx)

File: app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx (hunk 1 above)
Comment (rohitgeddam) [reply app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx:30]: I forgot to remove it. I will remove it on the next commit.

File: app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx (hunk 2 above)
Comment (rohitgeddam) [reply app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx:276]: Ok, i can do that

File: app/assets/javascripts/components/common/ArticleViewer/components/IconOpener.jsx (hunk 3 above)
Comment (rohitgeddam) [reply app/assets/javascripts/components/common/ArticleViewer/components/IconOpener.jsx]: ok, i will do it that way

File: config/locales/en.yml [hunk 4]
```diff
@@ -145,6 +145,7 @@ en:
     label: Activity
 
   articles:
+    article_not_found: 'Article not found'
```
Comment (ragesoss) [inline config/locales/en.yml:148]: "This article has not been created yet."

File: app/assets/javascripts/components/common/ArticleViewer/components/IconOpener.jsx [hunk 5]
```diff
@@ -1,19 +1,44 @@
...
+      </div>
+    )
 );
 
 IconOpener.propTypes = {
   showArticle: PropTypes.func.isRequired,
   showButtonClass: PropTypes.string,
-  showButtonLabel: PropTypes.func.isRequired
+  showButtonLabel: PropTypes.func.isRequired,
+  disabled: PropTypes.bool,
```
Comment (ragesoss) [inline app/assets/javascripts/components/common/ArticleViewer/components/IconOpener.jsx:34]: It doesn't use this prop now, right?
