### PR TITLE
Fixed bug in Article Viewer

### LINKED ISSUE #5769: Authorship data "Loading" message does not go away in Article Viewer if no current content is attributed to a student
### What is happening?
In the article viewer, if all of a student's work was removed from the article, the ArticleViewer often keeps showing the loading message in the footer even after the data has been received from the WikiWho server.

Also, the new 'Show last revision' feature will incorrectly show a highlighted color instead of the 'no attributed content' message if you load authorship data for that earlier revision and then switch back to the current revision with no remaining student work.

Also, switching between the 'last' and 'current' views does not cancel pending requests to the WikiWho server; I'm not sure whether it handles the data properly if it then receives (for example) the 'current' data while in 'last' mode or vice versa.

### To Reproduce

Here's a current example where this is happening:

https://dashboard.wikiedu.org/courses/Bentley_University/NAS_348_Global_Climate_Change_(Spring_2024)/students/articles/NorthShoreLife?showArticle=50887930

### Expected behavior
If the authorship data is received successfully and there is no student work, it should switch to the 'no attributed work' view.

### PR DESCRIPTION
**Pull request by om-chauhan1**
## What this PR does
Fixes #5769 
This pr fixes bugs in Article Viewer.

- [x] In the article viewer, if all of a student's work was removed from the article, the ArticleViewer will not keep showing the loading message

- [x] Switching between the 'last' and 'current' views is only allowed when there is no pending request to the WikiWho server.

## Video

After : 
For issue 1

[After1.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/8ee9e090-a94f-492a-8290-1846090b891b)

For issue 2

[After2.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/b155dc5a-e29e-4c07-ad22-d8b6ff54b5df)

### CODE REVIEW

**Comment by om-chauhan1** [comment]
@ragesoss Sir, in which example you have seen that :
This new 'Show last revision' feature incorrectly shows a highlighted colour instead of the 'no attributed content' message if we load authorship data for that earlier revision and then switch back to the current revision with no remaining student work.

**Comment by ragesoss** [comment]
@om-chauhan1 it was happening in the example I linked in the issue.

File: app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx [hunk 1]
```diff
@@ -189,13 +190,9 @@ const ArticleViewer = ({ showOnMount, users, showArticleFinder, showButtonLabel,
     if (editorsID.length) {
       // If there are unhighlighted editors, call the function to check their contributions in wikitext metadata
       usersContributionExists(editorsID);
-    } else {
-      const status = 'No Highlighted Editors';
-      // Set the unhighlightedEditors state with a status message to make legendStatus ready in the
-      // Footer Component for loading the authorship data
-      setUnhighlightedEditors([status]);
```
Comment (ragesoss) [inline app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx:196]: We don't want to get rid of this 'unhighlighted editors' feature, as it's very useful to show the user that we successfully received data but none of the editor's work is part of the received data.

**Comment by om-chauhan1** [comment]
@ragesoss Sir kindly see are these status correct, then i will proceed accordingly : 

Status diagram of Article Viewer

File: app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx (hunk 1 above)
Comment (ragesoss) [reply app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx:196]: Okay. If you see a good way to fix the bug such that the 'no highlghted editors' message shows appropriately (after data is successfully received but the relevant editors' IDs are not found in the data), please do so.

**Comment by ragesoss** [comment]
> @ragesoss Sir kindly see are these status correct, then i will proceed accordingly :
> 
> Status diagram of Article Viewer

I'm not 100% sure — I don't understand the prevHtml === nextHtml part — but it looks like you have the right idea.

One of the important bits is the handling of editors who don't have IDs that show up in the parsed authorship highlighting data... sometimes this is because of a problem with the data, even though that user actually has contributions to the current version, and sometimes it is because all their contributions were removed. You may want to explore the PR that implemented the handling of that: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5470

Note that 'editorsID' is an unhelpful variable name and should probably be changed, as it does not clearly communicate that these are IDs of editors who do not have highlighted content.

**Comment by om-chauhan1** [comment]
@ragesoss  Kindly have a look :
Cases :
1. When data is fetched successfully but the user has no contributions in the shown version of the Article :

https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/a939c0c2-c3c5-4568-a3a7-c5d88d7ea061


2. When user contributions exist but remain unhighlighted because of certain factors (mentioned in the message below):
 
[Demo 2.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/8a336e95-6223-4f57-b63c-cce438fa060c)


3. When no unhighlighted users exist :

[Demo 3.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/74e74602-f080-4644-93ab-4b6e0276faac)
