### PR TITLE
Fixed : On-wiki training_slide with quiz doesn't include complete question prompt

### LINKED ISSUE #5823: On-wiki training slide with quiz doesn't include complete question prompt
Here's a quiz slide: https://outreachdashboard.wmflabs.org/training/editing-wikipedia/plagiarism/close-paraphrasing-quiz

The wiki source page includes a quoted passage which does not show up on the Dashboard: https://meta.wikimedia.org/wiki/Training_modules/dashboard/slides/11511-close-paraphrasing-quiz

This may be a bug in WikiSlideParser, or somewhere else along the path to loading training content from a wiki page.

### PR DESCRIPTION
**Pull request by omChauhanDev**
## What this PR does
Fixes #5823

This PR improves quiz question formatting by:
- Adding multi-line support for quiz content parsing
- Removing unwanted wiki markup (colons and triple quotes) from rendered content
- Preserving proper line breaks and paragraph formatting

## Technical Changes
- Updated `template_parameter_value` in `WikiSlideParser` to handle multi-line content
- Modified regex pattern to safely remove wiki formatting characters
- Added markdown processing for quiz questions in the frontend Quiz component

## Screenshots
Before:
Before

After:
After

### CODE REVIEW

File: lib/training/wiki_slide_parser.rb [hunk 1]
```diff
@@ -216,9 +216,13 @@ def module_hash(template, module_number)
   end
 
   def template_parameter_value(template, parameter)
-    # Extract value from something like:
-    # | parameter_name = value
-    match = template.match(/\|\s*#{parameter}\s*=\s*(?<value>.*)/)
-    match && match['value']
+    # Extract value from the template
+    match = template.match(/\|\s*#{parameter}\s*=\s*(?<value>.*?)(?=\||\Z)/m)
```
Comment (ragesoss) [inline lib/training/wiki_slide_parser.rb:220]: This is a complicated regex, so it should include comments to explain what each part is doing.

Also, the example from the comment should not be removed. If necessary, update that example or add a second one for the case this is dealing with.

**Review by ragesoss — COMMENTED** [review]
This should include a new test in wiki_slide_parser_spec.rb, which fails without the update to WikiSlideParser but passes with it. The exact slide content from the bug report can probably be used for this.

**Comment by omChauhanDev** [comment]
## Screenshots (for test case)
Before updating WikiSlideParser:
Before

After updating WikiSlideParser:
After



## Testing
- Added new quiz with multi-line content
- Verified formatting in both backend parsing and frontend display
- Confirmed existing quiz functionality remains unchanged
