### PR TITLE
Remove usage deprecated component will receive props#3478

### LINKED ISSUE #3478: Refactor componentWillMount and componentWillReceiveProps
### What is happening?

componentWillMount and componentWillReceiveProps were producing warnings in the browser console, saying that use of the soon-to-be-depricated componentWillMount and componentWillReceiveProps has to be refactored and phased out. 

Commit [a0321daf12d62479d84eff5729dafce4089111bf](https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/3472/commits/a0321daf12d62479d84eff5729dafce4089111bf)
in PR #3472 renames these methods to the supported UNSAFE_ versions. 34 occurrences were replaced. 
 
The next step is to refactor these methods. 

### To Reproduce

1. Open dev code of project
2. Search whole project for UNSAFE_
3. See the React methods labeled UNSAFE_

### Expected behavior
A full refactor of the UNSAFE_ methods in accordance with the new React documentation.

### System Information

 - OS: MAC OS High Sierra Version 10.13.6
 - Browser Chrome Version 78.0.3904.70

### Additional context
From comment in PR #3472 
(This PR doesn't solve the issue, the conversation here explains the context)

> Hey @khyatisoneji, thanks for looking it over. I did notice the pre-existing warnings. Here is what I found. I am opening a separate issue to track that work: 
> 
> I looked at the errors and the React documentation. I tried changing `componentWillReceiveProps` in `app/assets/javascripts/components/revisions/diff-viewer.jsx` to `componentDidUpdate` and I am left with diffs that won't load. I tried the same for `app/assets/javascripts/components/common/article-viewer.jsx` with the same result.
> 
> I think that properly updating all the soon-to-be-deprecated `componentWillMount` and `componentWillReceiveProps` methods is going to be a separate refactoring using the new React version way of doing things. 
> 
> In the meantime, I ran this command from the documentation to rename such methods in `app/assets/javascripts`:
> 
> `npx react-codemod rename-unsafe-lifecycles` 
> 
> `componentWillReceiveProps()` -> `UNSAFE_componentWillReceiveProps()`
> `componentWillMount()` -> `UNSAFE_componentWillMount()`
> 
> 34 changes were made.
> 
> From [React Blog: Update on Async Rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)
> 
> > **Gradual Migration Path**
> > 
> > React follows semantic versioning, so this change will be gradual. Our current plan is:
> > 
> > **16.3:** Introduce aliases for the unsafe lifecycles, UNSAFE_componentWillMount, UNSAFE_componentWillReceiveProps, and UNSAFE_componentWillUpdate. (Both the old lifecycle names and the new aliases will work in this release.)
> > 
> > **A future 16.x release:** Enable deprecation warning for componentWillMount, componentWillReceiveProps, and componentWillUpdate. (Both the old lifecycle names and the new aliases will work in this release, but the old names will log a DEV-mode warning.)
> > 
> > **17.0:** Remove componentWillMount, componentWillReceiveProps, and componentWillUpdate . (Only the new “UNSAFE_” lifecycle names will work from this point forward.)
> >

### PR DESCRIPTION
**Pull request by shashwatkathuria**
## What this PR does
Fixes #3478 . Uses `componentDidUpdate` or/and `getDerivedStateFromProps` as required in the scenario. The method being removed is `UNSAFE_componentWillReceiveProps` .

### CODE REVIEW

File: app/assets/javascripts/components/article_finder/article_finder_row.jsx [hunk 1]
```diff
@@ -14,8 +14,9 @@ const ArticleFinderRow = createReactClass({
     };
   },
 
-  UNSAFE_componentWillReceiveProps(nextProps) {
-    if (this.state.isLoading && (this.props.assignment !== nextProps.assignment)) {
+  componentDidUpdate(prevProps, prevState) {
```
Comment (ragesoss) [inline app/assets/javascripts/components/article_finder/article_finder_row.jsx:17]: This would benefit from a comment explaining how we're using `isLoading` for two different situations and so need to do this in a weird way that violates the usual best practices.

File: app/assets/javascripts/components/course_creator/course_creator.jsx [hunk 2]
```diff
@@ -67,11 +67,9 @@ const CourseCreator = createReactClass({
   },
 
   UNSAFE_componentWillReceiveProps(nextProps) {
-    if (nextProps.course.school !== '' && nextProps.course.title !== '') {
-      this.state.tempCourseId = CourseUtils.generateTempId(nextProps.course);
-    } else {
-      this.state.tempCourseId = '';
-    }
+    this.setState({
```
Comment (ragesoss) [inline app/assets/javascripts/components/course_creator/course_creator.jsx:70]: I think this may result in behavior change when creating a new course.

The idea is that we don't want the current version of the course slug (ie, the tempCourseId) to show up in the CourseCreator modal at the bottom until after the user has added something for both school and title.

File: app/assets/javascripts/components/revisions/diff_viewer.jsx [hunk 3]
```diff
@@ -37,6 +37,18 @@ const DiffViewer = createReactClass({
     };
   },
 
+  // When 'show' is clicked, this component may or may not already have
+  // users data (a list of usernames) in its props. If it does, then 'show' will
+  // fetch the MediaWiki user ids, which are used for coloration. Those can't be
+  // fetched until the usernames are available, so 'show' will fetch the usernames
+  // first in that case. In that case, componentDidUpdate fetches the
+  // user ids as soon as usernames are avaialable.
+  componentDidUpdate(prevProps, prevState) {
```
Comment (ragesoss) [inline app/assets/javascripts/components/revisions/diff_viewer.jsx:46]: This looks fine, but did you test it out manually on the Articles tab of a course with edited articles, as well as the Students tab?

This is behavior that is pretty important, but I don't think it's tested in any of feature specs.

File: app/assets/javascripts/components/course_creator/course_creator.jsx (hunk 2 above)
Comment (ragesoss) [reply app/assets/javascripts/components/course_creator/course_creator.jsx:70]: Nevermind! I see that you moved that behavior into CourseUtils. Good!

File: app/assets/javascripts/training/components/quiz.jsx [hunk 4]
```diff
@@ -29,10 +29,6 @@ const Quiz = createReactClass({
     return this.setState({ selectedAnswerId: e.currentTarget.getAttribute('data-answer-id') });
   },
 
-  UNSAFE_componentWillReceiveProps(newProps) {
```
Comment (ragesoss) [inline app/assets/javascripts/training/components/quiz.jsx:32]: Remind me what's up with this file. I'm confused about how we're using state vs. props for keeping track of the selected answer. Was this bit of copying props over to state just unnecessary?

Are there better names we could use than `setAnswer` vs `setSelectedAnswer` to make it clear what's going on?

Comment (shashwatkathuria) [reply app/assets/javascripts/training/components/quiz.jsx:32]: Okay...So through `setAnswer`, we first update the choice user has chosen from the `e.currentTarget`. This update is done through setState (ofc), which means that the state is updated successfully. Now that this part is done as and when the user wants to change the option, now the user clicks on `CHECK ANSWER` which calls verifyAnswer which in turn calls `setSelectedAnswer`. Now, what `setSelectedAnswer` does is, that it updates the redux state through the action appropriately so that the user is able to go to the next slide if the option chosen is the same as `state.currentSlide.assessment.correct_answer_id`. `this.props.selectedAnswerId` is actually nothing in the process I just elaborated and so always comes out to be `undefined`. This is why I removed it.

File: app/assets/javascripts/components/revisions/diff_viewer.jsx (hunk 3 above)
Comment (shashwatkathuria) [reply app/assets/javascripts/components/revisions/diff_viewer.jsx:46]: Yes, I did check the `diff_viewer.jsx` manually (the popup that shows the differences in the revised version form the previous one). I'll submit its feature spec in a new PR.

File: app/assets/javascripts/components/article_finder/article_finder_row.jsx (hunk 1 above)
Comment (shashwatkathuria) [reply app/assets/javascripts/components/article_finder/article_finder_row.jsx:25]: Done!

**Comment by ragesoss** [comment]
@AmitJoki could you give this a review? I've gone through it a few times and don't notice anything else that I can suggest.

File: app/assets/javascripts/components/common/calendar.jsx [hunk 5]
```diff
@@ -23,6 +23,14 @@ const Calendar = createReactClass({
     updateCourse: PropTypes.func.isRequired
   },
 
+  statics: {
```
Comment (AmitJoki) [inline app/assets/javascripts/components/common/calendar.jsx:26]: If we won't be using any more static methods, it is better to go with `static getDerivedStateFromProps`, keeps the code concise.

File: app/assets/javascripts/components/common/calendar.jsx [hunk 6]
```diff
@@ -34,12 +42,6 @@ const Calendar = createReactClass({
     }
     return true;
   },
-  UNSAFE_componentWillReceiveProps(nextProps) {
-    if (nextProps.course.start !== moment(this.state.initialMonth).format('YYYY-MM-DD')) {
```
Comment (AmitJoki) [inline app/assets/javascripts/components/common/calendar.jsx:38]: is this condition not needed?

**Comment by AmitJoki** [comment]
I have left a comment @ragesoss . Also I think checkAnswer can be a bit ambiguous. How about `reviewAnswer`?

File: app/assets/javascripts/components/common/calendar.jsx (hunk 6 above)
Comment (shashwatkathuria) [reply app/assets/javascripts/components/common/calendar.jsx:38]: I talked to @ragesoss in Slack about this. Firstly the statement is being compared in a wrong way, i.e., ISO String to yyyy-mm-dd (ISO String contains both date and time). Secondly, when I corrected this comparison and shifted it to `getDerivedStateFromProps`, @ragesoss told me to leave this statement as we were calling `moment` twice in this and this is not really necessary and to leave this condition altogether.
