### PR TITLE
Fix pagination in Uploads

### LINKED ISSUE #2028: Pagination element disappears if we go to another tab and then come back to Uploads

### PR DESCRIPTION
**Pull request by aSquare14**
fixes #2028

### CODE REVIEW

File: app/assets/javascripts/components/uploads/uploads_handler.jsx [hunk 1]
```diff
@@ -13,18 +13,19 @@ const UPLOADS_PER_PAGE = 100;
...
 const UploadsHandler = createReactClass({
   displayName: 'UploadsHandler',
-
   propTypes: {
     course_id: PropTypes.string,
     course: PropTypes.object
   },
 
   getInitialState() {
+    const length_selecteduploads = this.props.selectedUploads.length;
```
Comment (ragesoss) [inline app/assets/javascripts/components/uploads/uploads_handler.jsx]: For style consistency, this should be done with camelCase, like `selectedUploadsLength`.

Alternatively you could just do the whole pageCount calculation inside the return object, without the intermediate const.

Comment (aSquare14) [reply app/assets/javascripts/components/uploads/uploads_handler.jsx]: @ragesoss  Done !
