### PR TITLE
Fixed Namespace-specific Stats Label

### LINKED ISSUE #5703: In namespace-specific stats, 'users' label always uses 'wiki_education' version
For example:

Screenshot 2024-03-08 at 10 00 00 AM

The label for the main stats on Programs & Events Dashboard courses is 'editors' (based on course type), but the label within the namespace stats is 'student editors'. That component should work the same way as elsewhere in terms of using the appropriate label based on the course type.

### PR DESCRIPTION
**Pull request by PR4NJ41**
## What this PR does
The label for the main stats is 'editors' (based on course type), but the label within the namespace stats is 'student editors'.

This PR fixes Namespace-specific Stats Label based on the course Type. 
fixes #5703 

## Screenshots

Before:
before PE

After:
after PE

### CODE REVIEW

File: app/assets/javascripts/components/common/OverviewStats/namespace_overview_stats.jsx [hunk 1]
```diff
@@ -2,7 +2,13 @@ import React from 'react';
 import PropTypes from 'prop-types';
 import OverviewStat from './overview_stat';
 
-const NamespaceOverviewStats = ({ statistics }) => {
+const NamespaceOverviewStats = ({ course, statistics }) => {
+  let student_editors_stat_msg;
+  if (course.type === 'ClassroomProgramCourse') {
```
Comment (ragesoss) [inline app/assets/javascripts/components/common/OverviewStats/namespace_overview_stats.jsx:7]: You can use CourseUtils.i18n here to handle the if/else behavior. See how it's used in course_alerts.jsx, for example.

Comment (PR4NJ41) [reply app/assets/javascripts/components/common/OverviewStats/namespace_overview_stats.jsx]: @ragesoss Thanks Sir, I have updated the code

**Comment by PR4NJ41** [comment]
@ragesoss This PR is ready for Review. Please review it. Thank You!
