### PR TITLE
Fix NotSignedInError to redirect with UI instead of plain text

### LINKED ISSUE #6658: NotSignedInError results in plain "Please sign in" message with no UI for signing in
Any action that requires the user to be signed in will throw a `NotSignedInError`, which is handled via `lib/errors/rescue_errors.rb`.

Currently, it's a plain text response that simply says "Please sign in", but the navbar is not rendered so there's no way to log in. Ideally, doing something that triggers such an error would both give the user an obvious way to proceed to login, and also redirect to the original intended location after successful login.

One context where this is relevant is the followup questionnaire links in AI alert emails, so that could be a good example for building a test for, as part of implementing this.

### PR DESCRIPTION
**Pull request by nexpectArpit**
Fixes #6658

### What this PR does

This PR improves the experience when a signed-out user visits a protected page.

- Replaces the plain text **“Please sign in”** response with a proper **401 Unauthorized** page.
- Stores the intended destination in the session and automatically returns the user to that page after a successful Wikipedia login.
- Download Safety: Detects if the return path is a download-only endpoint (like /ungreeted) and redirects the user to the home page with a clear download link. This prevents the browser from getting stuck on the Wikipedia "Allow" page during silent file downloads.
- Security: Validates redirection paths to prevent open-redirect vulnerabilities.
- Tests: Adds unit tests for the redirection and security logic in ApplicationController.

### Screenshots

**Before**  
Screenshot 2026-02-05 at 3 58 15 AM

**After**  
Screenshot 2026-02-13 at 9 47 25 PM

@ragesoss

### CODE REVIEW

**Comment by nexpectArpit** [comment]
@ragesoss, I have considered the feedback of my copilot and made the changes. Kindly review it.

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -27,7 +27,24 @@ def after_sign_out_path_for(_resource_or_scope)
...
+    # Security: ensure path is a relative path to prevent open redirects
+    begin
+      uri = URI.parse(path)
+      path = uri.path if uri.host
+      path = '/' unless path.start_with?('/')
+    rescue URI::InvalidURIError
+      path = '/'
+    end
+
+    if path.include?('ungreeted') || path.include?('csv')
```
Comment (ragesoss) [inline app/controllers/application_controller.rb:44]: It's not clear to me what's going on here. Why are `ungreeted` and `csv` paths special-cased here?

File: db/schema.rb [hunk 2]
```diff
@@ -10,16 +10,26 @@
 #
 # It's strongly recommended that you check this file into your version control system.
 
-ActiveRecord::Schema[7.0].define(version: 2025_07_28_182700) do
-  create_table "alerts", id: :integer, charset: "utf8mb4", force: :cascade do |t|
+ActiveRecord::Schema[7.0].define(version: 2026_01_27_212149) do
```
Comment (ragesoss) [inline db/schema.rb:13]: Schema changes are not expected here.

Comment (ragesoss) [reply db/schema.rb:13]: It looks like our schema file is out of date and didn't get updated after recent migrations. But that's not relevant to this PR, so the schema change here should be excluded.

File: spec/controllers/application_controller_spec.rb [hunk 3]
```diff
@@ -236,4 +238,43 @@ def index
...
+    it 'falls back to omniauth.origin' do
+      request.env['omniauth.origin'] = '/origin'
+      expect(controller.after_sign_in_path_for(user)).to eq('/origin')
+    end
+
+    it 'defaults to root path' do
+      expect(controller.after_sign_in_path_for(user)).to eq('/')
+    end
+
+    it 'validates return_to to prevent open redirects' do
```
Comment (ragesoss) [inline spec/controllers/application_controller_spec.rb]: I'm not clear on what situation is being tested here.

File: app/views/errors/unauthorized.html.haml [hunk 4]
```diff
@@ -0,0 +1,14 @@
+- content_for :after_title, ' - Sign In Required'
+
+%header.main-page
+  .container
+    %h1= t('error_401.header', default: 'Sign In Required')
```
Comment (ragesoss) [inline app/views/errors/unauthorized.html.haml]: I think this is a pretty aggressive for a 'you need to sign in' message. It's fine for a 401 where the user is not signed in but not allowed to do what they tried to do, but I think for the specific case of needing to log in, the header is not necessary.

**Review by ragesoss — COMMENTED** [review]
This looks like a reasonable approach overall.

File: app/controllers/application_controller.rb (hunk 1 above)
Comment (nexpectArpit) [reply app/controllers/application_controller.rb:44]: It's just to make things less confusing. Since those links are only for downloading files or seeing raw data, sending a user straight there right after they log in can make it look like the site didn't load properly or just went to a blank page.

Sending them to the homepage with a clear 'Download here' link in the success message ensures they have successfully logged in and creates a smoother experience.

File: db/schema.rb (hunk 2 above)
Comment (nexpectArpit) [reply db/schema.rb:13]: After updating the PR, I have reverted <unk> db/schema.rb<unk> to the expected version and made the necessary changes, thanks for pointing it out.

File: spec/controllers/application_controller_spec.rb (hunk 3 above)
Comment (nexpectArpit) [reply spec/controllers/application_controller_spec.rb]: This test covers two simple cases around where a user is sent after login.
- First, it checks what happens if the stored return link points outside our site. In that case, the code ignores the unsafe part and sends the user to a safe internal page instead.
- Second, it checks the fallback behavior. If the return link is missing or broken, the app does not error out and redirects the user to the home page.

Actually I implemented these tests after considering feedback of co-pilot .
So the test makes sure the user always lands on a valid, safe page after login, regardless of what value ends up in the session.

File: app/views/errors/unauthorized.html.haml (hunk 4 above)
Comment (nexpectArpit) [reply app/views/errors/unauthorized.html.haml]: i implemented  the changes, have a look!

File: app/controllers/application_controller.rb (hunk 1 above)
Comment (ragesoss) [reply app/controllers/application_controller.rb:44]: Okay. That should be explained in a comment.

**Comment by ragesoss** [comment]
Please update the screenshot and clean up the commit history.

**Comment by nexpectArpit** [comment]
@ragesoss I cleaned the commit history and updated the Screenshot!

File: config/locales/ar.yml [hunk 5]
```diff
@@ -1604,7 +1604,7 @@ ar:
       IP الخاص بك بواسطة Wikipedia أو وصل بالفعل إلى الحد اليومي للحسابات الجديدة.  حاول
       الاتصال من شبكة مختلفة.
   error_401:
-    header: غير مصرح. >:-(
```
Comment (ragesoss) [inline config/locales/ar.yml:1613]: Rather than change this header message, I think it makes more sense to just not use the header in this particular case.  The header with the frown is still okay for other 401 situations. (When we do make changes to already-translated interface messages, we normally only change the English, as all the other locale files are basically maintained indirectly via translatewiki.net.)

**Comment by ragesoss** [comment]
This looks like it has some unrelated changes, including CI and i18n. Those should be in separate PRs. This one should only include the changes directly related to the signin error.

**Comment by nexpectArpit** [comment]
@ragesoss I noticed the build is failing on the test setup again. I  included those Redis changes in the first place because they seemed to be the only way to get the build to actually pass.
I've taken them out now to keep this PR focused strictly on the UI work as you asked, but now we're back to a failing build. If I move that setup fix to a separate PR, this UI one is going to stay 'red' for a while.

What’s the best way to move forward here? Should I put that fix back in just to get the green light on this PR, or are you okay with this one staying red while I handle the setup fix separately?

**Comment by ragesoss** [comment]
@nexpectArpit i tried copying over those CI changes, but the build still failed. Not sure what's going on with that! But if you can get a PR that does fix CI, please do.

**Comment by nexpectArpit** [comment]
@ragesoss I'm a bit confused to handle the PR though. just want a clarification like I can raise my original PR again, but it has everything together like the CI fix, the i18n changes, and the UI stuff. Would you prefer me to just raise that original one, or should I try to separate them? I'm just still a bit confused about the right way to do it when the changes are mixed like that.

Also, I wanted to check if you're seeing a lot of linting warnings on your side too? I'm getting about 220 warnings (mostly about 'literal strings') in my local setup, and I even see them when I'm on the master branch. I just want to be sure it's not some issue that is only happening on my side.

**Comment by ragesoss** [comment]
I'd prefer separate PRs. The CI issue is not related to this, so it should be fixed on its own in a different PR.

The string literal warnings appear locally for all the JS components that have string literals instead of i18n messages. Fixes for these warnings in components that you're changing for a given issue is fine to include, but it should be limited to the components where other changes are required.

**Comment by nexpectArpit** [comment]
@ragesoss I've raised a separate PR for the CI fix: #6674

There were actually two issues causing the CI failure:
- The Redis action was hitting Docker Hub rate limits
- The MariaDB action was using a Docker client version (1.40) that's too old for the current GitHub runners (minimum 1.44)

I replaced both with native GitHub Actions service containers. Once that PR is merged, the CI on this PR should pass!

**Comment by ragesoss** [comment]
Great! You should rebase this branch so we can get a clean CI run.

**Comment by nexpectArpit** [comment]
@ragesoss have a look.
