### PR TITLE
Fix: mainspace article validation for ClassroomProgramCour…

### LINKED ISSUE #6531: When assigning an article for a ClassroomProgramCourse, only mainspace titles should be allowed
Currently, it's possible to add an assigned article that isn't in mainspace, and this breaks some of the features that expect a mainspace title (and is just not a supported way to do things).

At last for the ClassroomProgramCourse type, the assign UI for editing articles should check whether the input is in a different namespace or is otherwise not a valid mainspace title, and throw an error message rather than submitting such an assignment.

For example, entering a URL for a category page (or the full title including Category: prefix) should result in the error message: `https://en.wikipedia.org/wiki/Category:1993_in_sports_in_Alberta`

### PR DESCRIPTION
**Pull request by Formasitchijoh**
## What this PR does
This PR resolves #6531 by cleaning up #6547 it adds a client-side mainspace article validation for ClassroomProgramCourse assignments for single and multi_wiki_assignment.This fix prevents broken assignments (e.g. Category:, Talk:, User: pages) that break stats, ArticleViewer, and impact tracking.

## AI usage
Used AI to understand the recursive chainSubmission method in the `add_available_article.jsx`  file  , Equally to catch edge cases for clearing  and displaying notification if an article title is invalid.

## Screenshots

https://www.loom.com/share/b7307c8073da4d00b438dac4ef544e31

## Open questions and concerns
@ragesoss should wikimedia incubator articles like `https://incubator.wikimedia.org/wiki/Wp/kiu/Heyder_Cansa ` be allowed or only mainspace articles are allowed for `ClassroomProgramCourses`

### CODE REVIEW

**Comment by ragesoss** [comment]
ClassroomProgramCourse is only used for Wiki Education Dashboard, and we don't have courses working on Incubator, so I think there's no need to handle that case.

File: app/assets/javascripts/actions/article_actions.js [hunk 1]
```diff
@@ -112,6 +112,53 @@ export const crossCheckArticleTitle = (articleId, articleTitle, article_mw_page_
   };
 };
 
+export const verifyMainSpaceArticle = (articleTitle, language = 'en', project = 'wikipedia') => {
```
Comment (ragesoss) [inline app/assets/javascripts/actions/article_actions.js]: There's a lot going on here, so it would be good explain in comments what all this method is intended to do. What is the strategy for verifying that it's a mainspace article?

In what situation will the default language and project values be used? When a title in added in the UI, normally this should be treated as an article title on the home wiki of the course (which may not be English), unless the wiki picker has been used to set a different wiki. In either case, we ought to know enough to provide a language and project before calling this method.

File: app/assets/javascripts/actions/article_actions.js [hunk 2]
```diff
@@ -112,6 +112,53 @@ export const crossCheckArticleTitle = (articleId, articleTitle, article_mw_page_
...
+
+      if (!response.ok) {
+        throw new Error(`API request failed with status ${response.status}`);
+      }
+      const data = await response.json();
+      const pages = data?.query?.pages;
+      const page = pages ? Object.values(pages)[0] : null;
+
+      if (!page || page.missing) {
+        return { valid: false, message: `The article does not exist on ${domain}` };
```
Comment (ragesoss) [inline app/assets/javascripts/actions/article_actions.js]: How does this work? We expect article titles that don't exist (and we just need to make sure they are valid potential mainspace titles), and I was able to add non-existent assigned articles without seeing this error message. Is there a particular situation where this should be triggered?

File: spec/features/multiwiki_assignment_spec.rb [hunk 3]
```diff
@@ -87,14 +88,16 @@
       expect(button).to have_content 'Assign/remove an article'
       button.click
       within('#users') do
-        first('input').set('https://wikisource.org/wiki/Heyder_Cansa', rapid: false)
+        first('input').set('https://en.wikisource.org/wiki/Alice%27s_Adventures_in_Wonderland',
```
Comment (ragesoss) [inline spec/features/multiwiki_assignment_spec.rb]: I think the appropriate fix for these specs is to use a different course type, rather than change the examples. We do still want to be able to support the wikisource.org example and test for regressions, it's just not relevant for ClassroomProgramCourse.

File: spec/features/multiwiki_assignment_spec.rb [hunk 4]
```diff
@@ -124,4 +128,28 @@
...
+rapid: false)
+      end
+
+      click_button 'Assign'
+      sleep 1
+      visit "/courses/#{course.slug}/students/articles"
+      find('.student-selection .student').click
+
+      within('#users') do
+        expect(page).to have_no_content('Category:1993 in sports in Alberta')
```
Comment (ragesoss) [inline spec/features/multiwiki_assignment_spec.rb:228]: It would be good to also check for the expected error message here. Simply checking for `have_no_content` can easily miss breaking changes.

File: spec/features/multiwiki_assignment_spec.rb [hunk 5]
```diff
@@ -124,4 +128,28 @@
...
+      find('.assign-button', text: 'Assign/remove an article').click
+
+      within('#users') do
+        find('input').set('https://en.wikipedia.org/wiki/Category:1993_in_sports_in_Alberta', 
+rapid: false)
+      end
+
+      click_button 'Assign'
+      sleep 1
+      visit "/courses/#{course.slug}/students/articles"
```
Comment (ragesoss) [inline spec/features/multiwiki_assignment_spec.rb]: Try to write the test in a way that does not require a second call to `visit` to reload the page, which will make the `sleep` unnecessary. Instead, you can write an expectation based on some visible change you expect on the page after clicking `Assign`.

File: spec/features/multiwiki_assignment_spec.rb [hunk 6]
```diff
@@ -36,6 +36,7 @@
         )
       end
       click_button 'Assign'
+      sleep 1
```
Comment (ragesoss) [inline spec/features/multiwiki_assignment_spec.rb]: As much as possible, we want to avoid adding `sleep` to feature specs, as it adds up and makes the test suite take longer than necessary.

Tests that sometimes fail without `sleep` can usually be rewritten in a way to avoid it, such as writing an expectation that indicates the completion of whatever step needs to happen.

**Comment by ragesoss** [comment]
I tested this locally, and it works nicely!

File: app/assets/javascripts/actions/article_actions.js (hunk 1 above)
Comment (Formasitchijoh) [reply app/assets/javascripts/actions/article_actions.js]: Oh I think i missed that, Just to clarify

Remove the default `language` and `project`  in the method since each course will have a home_wiki it is tracking, hence should use that to verify the article

File: app/assets/javascripts/actions/article_actions.js (hunk 2 above)
Comment (Formasitchijoh) [reply app/assets/javascripts/actions/article_actions.js]: No particular situation it should work if the article does not exist if the response object for the page has a missing attribute. Can you link the article you used to test this

**Comment by ragesoss** [comment]
LGTM!
