### PR TITLE
Solved bug of next estimated update

### LINKED ISSUE #5489: Course update info is misleading for non-current courses
### What is happening?
On course pages, a small message below the header stats shows info about the update process: when the last update was completed, and (if it's in the future) when the next update is expected.

For a course that ended and stopped receiving updates, but then was updated via a manual update or via the 'Schedule Data Update' button, after the update is complete, the update info says something like "Next estimated update: in 6 days." This happens because it takes the average time between updates for the last 10 updates to estimate the time of next update, but for a course that has ended and is no longer in the update window (by default, 30 days after the end of the course, based on a setting in application.yml), this is misleading because no further updates are expected.

### PR DESCRIPTION
**Pull request by om-chauhan1**
## What this PR does
Fixes #5489 
This PR solves the a bug of next estimated update which is misleading previously.
 I have created the same scenario as mentioned in the issue(as shown in before screenshot) and then added the logic of checking whether the calculated estimated date is within the range of 30 days (after course end date) or not.

## Screenshots
Before:

Before

After:

After

### CODE REVIEW

**Comment by om-chauhan1** [comment]
@ragesoss Sir, this test is also failing prior to the changes done in this pr i.e in master branch also.

File: app/assets/javascripts/utils/statistic_update_info_utils.js [hunk 1]
```diff
@@ -19,11 +19,12 @@ const getLastUpdateMessage = (course) => {
   let nextUpdateMessage = '';
   let isNextUpdateAfter = false;
   const lastUpdateMoment = lastSuccessfulUpdateMoment(course.flags.update_logs);
+  const updatesEndMoment = toDate(course.update_until);
   if (lastUpdateMoment) {
     const averageDelay = course.updates.average_delay ?? 0;
     lastUpdateMessage = `${I18n.t('metrics.last_update')}: ${formatDistanceToNow(lastUpdateMoment, { addSuffix: true })}.`;
     const nextUpdateExpectedTime = addSeconds(lastUpdateMoment, averageDelay);
-    isNextUpdateAfter = isAfter(nextUpdateExpectedTime, new Date());
+    isNextUpdateAfter = (isAfter(nextUpdateExpectedTime, new Date()) && isAfter(updatesEndMoment, new Date()));
```
Comment (ragesoss) [inline app/assets/javascripts/utils/statistic_update_info_utils.js:27]: This works as expected, but it's not going to be obvious to future coders what the purpose of this line is, and the logic is duplicated in the other method.

Can the check against the end-of-updates date be extracted to another method so there's less duplication and there's a method name that makes the purpose more clear?

**Review by ragesoss — CHANGES_REQUESTED** [review]

File: app/assets/javascripts/utils/statistic_update_info_utils.js (hunk 1 above)
Comment (om-chauhan1) [reply app/assets/javascripts/utils/statistic_update_info_utils.js:27]: sure, i have extracted it to another method.
